# -*- coding: utf-8 -*-
"""MNIST_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LrdKFbuPR675h69qhtib5rh3Do2T1e2K

# Making a CNN to classify digits from the 'MNIST' dataset

## 1. Setup our libraries and dataset
"""

import torch
from torch import nn
import torchvision
from torchvision import datasets
from torchvision import transforms
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt

"""### 1.1 Import dataset"""

# Setup Training data
from torchvision import datasets
train_data = datasets.MNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
    target_transform=None
)

test_data = datasets.MNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
    target_transform=None
)

len(train_data), len(test_data)

# See the first training example
image, label = train_data[0]
image, label

class_names = train_data.classes
class_names

class_to_idx = train_data.class_to_idx
class_to_idx

train_data.targets

# Check the shape of our image
print(f"Image shape: {image.shape} -> [color_channels, height, width]")
print(f"Image label: {class_names[label]}")

import matplotlib.pyplot as plt
image, label = train_data[0]
print(f"Image shape: {image.shape}")
plt.imshow(image.squeeze(), cmap="gray")
plt.title(class_names[label])
plt.axis(False)

# Plot more images
torch.manual_seed(42)
fig = plt.figure(figsize=(9,9))
rows, cols = 4, 4
for i in range(1, rows*cols+1):
  random_idx = torch.randint(0, len(train_data), size=[1]).item()
  img, label = train_data[random_idx]
  fig.add_subplot(rows, cols, i)
  plt.imshow(img.squeeze(), cmap="gray")
  plt.title(class_names[label])
  plt.axis(False);

train_data, test_data

"""### 1.2 Setting up dataloader for Mini Batch training"""

from torch.utils.data import DataLoader

# Setup the batch size hyperparameter
BATCH_SIZE_TRAIN = 32
BATCH_SIZE_TEST = 32
# Turn datasets into iterables (batches)
train_dataloader = DataLoader(dataset=train_data,
                              batch_size=BATCH_SIZE_TRAIN,
                              shuffle=True)

test_dataloader =DataLoader(dataset=test_data,
                            batch_size=BATCH_SIZE_TEST,
                            shuffle=False)
train_dataloader, test_dataloader

len(train_dataloader), len(test_dataloader)

"""### 1.3 Getting some helper functions"""

import requests
from pathlib import Path

# Download helper functions form help Pytorch repo if not done

if Path("helper_functions.py").is_file():
  print("helper_functions.py already exists")
else:
  print("Downloding helper_functions.py")
  request = requests.get("https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/helper_functions.py")
  with open("helper_functions.py", "wb") as f:
    f.write(request.content)

from timeit import default_timer as timer
def print_train_time(start: float,
                     end: float,
                     device: torch.device = None):
  """Prints difference between start and end time."""
  total_time = end - start
  print(f"Train time on {device}: {total_time: .3f} seconds")
  return total_time

# Setup device agnostic code
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
device

"""## 2. Training and evaluating the model

### 2.1 Setting up Training, Testing and evaluation code for the model(s)
"""

def train_step(model: torch.nn.Module,
               data_loader: torch.utils.data.DataLoader,
               loss_fn: torch.nn.Module,
               optimizer: torch.optim.Optimizer,
               accuracy_fn,
               device: torch.device = device):
  """ Performs a training step with model trying to learn on data_loader"""
  train_loss, train_acc = 0, 0
  train_accs_iter = []
  # Put model in training mode
  model.train()

  # Add a loop to loop through training batches
  for batch, (X, y) in enumerate(data_loader):
    # Put data on target device
    X, y = X.to(device), y.to(device)

    # 1. Forward pass
    y_pred = model(X)

    # 2. Calculate loss and accuracy (per batch)
    loss = loss_fn(y_pred, y)
    train_loss += loss
    temp_acc = accuracy_fn(y_true=y,
                           y_pred=y_pred.argmax(dim=1))
    train_accs_iter.append(temp_acc)
    train_acc +=temp_acc

    # 3. Optimizer zero grad
    optimizer.zero_grad()

    # 4. Loss backward
    loss.backward()

    # 5. Optimizer step
    optimizer.step()


  # Divide total train loss and acc by length of train dataloader
  train_loss /= len(data_loader)
  train_acc /= len(data_loader)
  print(f"Train loss: {train_loss:.5f} | Train acc: {train_acc:.2f}%")
  return train_loss, train_acc, train_accs_iter

def test_step(model: torch.nn.Module,
              data_loader: torch.utils.data.DataLoader,
              loss_fn: torch.nn.Module,
              accuracy_fn,
              device: torch.device = device):
  """Performs a tesitng loop step on model going over data_loader"""
  test_loss, test_acc = 0, 0
  test_accs_iter = []
  # Put model in eval mode
  model.eval()

  # Turn on inference mode
  with torch.inference_mode():
    for X, y in data_loader:
      # Senf the data to the target device
      X, y = X.to(device), y.to(device)

      # 1. Forward pass
      test_pred = model(X)

      # 2. Calculate the loss/acc
      test_loss += loss_fn(test_pred, y)
      temp_acc = accuracy_fn(y_true=y,
                             y_pred=test_pred.argmax(dim=1))
      test_accs_iter.append(temp_acc)
      test_acc += temp_acc

    # Adjust metrics and print out
    test_loss /= len(data_loader)
    test_acc /= len(data_loader)
    print(f"Test loss: {test_loss:.5f} | Test acc: {test_acc:.2f}%\n")
    return test_loss, test_acc, test_accs_iter

def eval_model(model: torch.nn.Module,
               data_loader: torch.utils.data.DataLoader,
               loss_fn: torch.nn.Module,
               accuracy_fn,
               device: torch.device = device):
  """Returns a dictionary containing results of model predicting on data loader"""
  loss, acc = 0, 0
  model.eval()
  with torch.inference_mode():
    for X, y in tqdm(data_loader):

      X, y = X.to(device), y.to(device)

      # Make predictions
      y_pred = model(X)

      # Accumulate the loss and acc values per batch
      loss += loss_fn(y_pred, y)
      acc += accuracy_fn(y_true=y,
                         y_pred=y_pred.argmax(dim=1))

    # Scale loss and acc to find avg loss/acc per batch
    loss /= len(data_loader)
    acc /= len(data_loader)

  return {"model_name": model.__class__.__name__,
          "model_loss": loss.item(),
          "model_acc": acc}

"""### 2.2 Making the model"""

# Create a convolutional Neural Network
class MNISTModel(nn.Module):
  def __init__(self, input_shape: int, hidden_units: int, output_shape: int):
    super().__init__()
    self.conv_block_1 = nn.Sequential(
        nn.Conv2d(in_channels=input_shape,
                  out_channels=hidden_units,
                  kernel_size=3,
                  stride=1,
                  padding=1),
        nn.ReLU(),
        nn.Conv2d(in_channels=hidden_units,
                  out_channels=hidden_units,
                  kernel_size=3,
                  stride=1,
                  padding=1),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size=2)
    )
    self.conv_block_2 = nn.Sequential(
        nn.Conv2d(in_channels=hidden_units,
                  out_channels=hidden_units,
                  kernel_size=3,
                  stride=1,
                  padding=1),
        nn.ReLU(),
        nn.Conv2d(in_channels=hidden_units,
                  out_channels=hidden_units,
                  kernel_size=3,
                  stride=1,
                  padding=1),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size=2)
    )
    self.classifier = nn.Sequential(
        nn.Flatten(),
        nn.Linear(in_features=hidden_units*7*7,
                  out_features=output_shape)
    )

  def forward(self, x):
    x = self.conv_block_1(x)
    #print(f"Output shape of conv block 1: {x.shape}")
    x = self.conv_block_2(x)
    #print(f"Output shape of conv block 2: {x.shape}")
    x = self.classifier(x)
    #print(f"Output shape of classifier: {x.shape}")

    return x

torch.manual_seed(42)
model = MNISTModel(input_shape=1,
                              hidden_units=10,
                              output_shape=len(class_names)).to(device)

# install torchinfo, import if its available
try:
  import torchinfo
except:
  !pip install torchinfo
  import torchinfo

from torchinfo import summary
summary(model, input_size=(1, 1, 28, 28))

# Setup loss function/eval metrics/optimizer
from helper_functions import accuracy_fn

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(params=model.parameters(),
                            lr=0.1)

"""### 2.3 Training"""

from tqdm.auto import tqdm
torch.manual_seed(42)
torch.cuda.manual_seed
# Measure time
from timeit import default_timer as timer
train_time_start_model = timer()
train_accs = []
test_accs = []
train_losses = []
test_losses = []

# Set epochs
epochs = 45

# Create a optimization and evaluation loop using train_step() and test_step()

for epoch in tqdm(range(epochs)):
  print(f"Epoch: {epoch}\n--------")
  train_loss, train_acc, train_accs_iter = train_step(model=model,
             data_loader=train_dataloader,
             loss_fn=loss_fn,
             optimizer=optimizer,
             accuracy_fn=accuracy_fn,
             device=device)
  train_losses.append(train_loss.cpu().item())
  train_accs.append(train_acc)
  test_loss, test_acc, test_accs_iter = test_step(model=model,
            data_loader=test_dataloader,
            loss_fn=loss_fn,
            accuracy_fn=accuracy_fn,
            device=device)
  test_losses.append(test_loss.cpu().item())
  test_accs.append(test_acc)

train_time_end_model = timer()
total_train_time_model = print_train_time(start=train_time_start_model,
                                            end=train_time_end_model,
                                            device=device)

"""### 2.4 Loss curve"""

plt.plot(range(epochs), train_losses, label="Train loss")
plt.plot(range(epochs), test_losses, label="Test loss")
plt.title("Loss curves")
plt.ylabel("Loss")
plt.xlabel("Epochs")
plt.legend()
plt.show()

"""### 2.5 Accuracy over epochs"""

plt.plot(range(epochs), train_accs, label="Train accuracy")
plt.plot(range(epochs), test_accs, label="Validation accuracy")
plt.title("Accuracy over epochs on MNIST Dataset")
plt.ylabel("Accuracy")
plt.xlabel("Epochs")
plt.legend()
plt.show()
print("Train Accuracy")
for i in train_accs:
  print(i/100)
print("\n Test accuracy \n")
for i in test_accs:
  print(i/100)

# Get model results
model_results = eval_model(
    model=model,
    data_loader=test_dataloader,
    loss_fn=loss_fn,
    accuracy_fn=accuracy_fn,
    device=device
)
model_results

"""### Making Predictions using our model"""

def make_predictions(model: torch.nn.Module,
                     data: list,
                     device: torch.device = device):
  pred_probs = []
  model.to(device)
  model.eval()
  with torch.inference_mode():
    for sample in data:
      # Prepare the samole
      sample = torch.unsqueeze(sample, dim=0).to(device)

      # Forward pass
      pred_logit = model(sample)

      # Get prediction probability
      pred_prob = torch.softmax(pred_logit.squeeze(), dim=0)

      # Get pred_prob off the GPU for further calculations
      pred_probs.append(pred_prob.cpu())

  # Stack the pred_prob to turn the list into a tensor
  return torch.stack(pred_probs)

"""### 2.6 Random Sampler
Run this cell to
"""

import random
#random.seed(42)
test_samples = []
test_labels = []
for sample, label in random.sample(list(test_data), k=9):
  test_samples.append(sample)
  test_labels.append(label)

# Make predictions
pred_probs = make_predictions(model=model,
                              data=test_samples)

# conver prediction probabilities into labels
pred_classes = pred_probs.argmax(dim=1)

# Plot predictions
plt.figure(figsize=(9,9))
nrows = 3
ncols = 3
for i, sample in enumerate(test_samples):
  # Create subplot
  plt.subplot(nrows, ncols, i+1)

  # Plot the target image
  plt.imshow(sample.squeeze(), cmap="gray")

  # Find the prediction (in text form)
  pred_label = class_names[pred_classes[i]]

  # Get the truth label(in text form)
  truth_label = class_names[test_labels[i]]

  # Create a title for the plot
  title_text = f"Pred: {pred_label} | Thruth: {truth_label}"

  # Check for equality between pred and truth and change color of title text
  if pred_label == truth_label:
    plt.title(title_text, fontsize=10, c="g")
  else:
    plt.title(title_text, fontsize=10, c="r")
  plt.axis(False)